# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  # FYI: If cross-platform build issues happen, then stop caching the modules in the volume.
  # build windows
  - name: 'mirror.gcr.io/library/golang'
    env: ['GOOS=windows', 'GOARCH=amd64', 'CGO_ENABLED=0', 'GO111MODULE=on']
    args: ['go', 'build', '-ldflags', '-X main.version=${BRANCH_NAME}', '-o', '/workspace/bin/${BRANCH_NAME}/windows_amd64/kpt.exe', '.']
    dir: '/workspace/'
    volumes:
      - name: go-modules
        path: /go

  # build linux
  - name: 'mirror.gcr.io/library/golang'
    env: ['GOOS=linux', 'GOARCH=amd64', 'CGO_ENABLED=0', 'GO111MODULE=on']
    args: ['go', 'build', '-ldflags', '-X main.version=${BRANCH_NAME}', '-o', '/workspace/bin/${BRANCH_NAME}/linux_amd64/kpt', '.']
    dir: '/workspace/'
    volumes:
      - name: go-modules
        path: /go

  # build darwin
  - name: 'mirror.gcr.io/library/golang'
    env: ['GOOS=darwin', 'GOARCH=amd64', 'CGO_ENABLED=0', 'GO111MODULE=on']
    args: ['go', 'build', '-ldflags', '-X main.version=${BRANCH_NAME}', '-o', '/workspace/bin/${BRANCH_NAME}/darwin_amd64/kpt', '.']
    dir: '/workspace/'
    volumes:
      - name: go-modules
        path: /go

  # build docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/kpt:${BRANCH_NAME}', '.' ]

  # run e2e tests and linting
  - name: 'mirror.gcr.io/library/golang'
    args: ['git', 'config', '--global', 'user.email', 'you@example.com']
    dir: '/workspace'
    volumes:
      - name: home
        path: /root
  - name: 'mirror.gcr.io/library/golang'
    args: ['git', 'config', '--global', 'user.name', 'Your Name']
    dir: '/workspace'
    volumes:
      - name: home
        path: /root
  - name: 'mirror.gcr.io/library/golang'
    args: ['make', 'all']
    env: ['GO111MODULE=on']
    dir: '/workspace'
    volumes:
      - name: go-modules
        path: /go
      - name: home
        path: /root

  # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kpt:${BRANCH_NAME}']

  # push the binaries
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '-a', 'public-read', '/workspace/bin/', 'gs://kpt-dev/']

timeout: '60m'
