---
# Source: mysql/templates/pvc.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-mysql
  namespace: default
  labels:
    app: release-name-mysql
    chart: "mysql-1.3.1"
    release: "release-name"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
