---
# Source: mysql/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: release-name-mysql
  namespace: default
  labels:
    app: release-name-mysql
    chart: "mysql-1.3.1"
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:
  
  mysql-root-password: "ZTdQVERPUXlteQ=="
  
  
  mysql-password: "YW44eUtvSHl3aA=="
  